# Generated by Django 3.1.7 on 2021-03-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodbanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('organisedby', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('blood_availability', models.BooleanField(default=False)),
                ('plasma_availability', models.BooleanField(default=False)),
                ('timings', models.TextField(default='24/7')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('fund_donations', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneNum', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('bloodType', models.CharField(max_length=10)),
                ('NumDonations', models.IntegerField(default=0)),
                ('NumRequests', models.IntegerField(default=0)),
                ('FundDonations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bloodstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodType', models.CharField(max_length=10)),
                ('plasma', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.donor')),
            ],
        ),
    ]
