# Generated by Django 3.1.7 on 2021-03-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstore',
            name='bloodType',
            field=models.CharField(default="don't know", max_length=10),
        ),
    ]
