# Generated by Django 3.1.7 on 2021-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210315_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(default='None', max_length=254)),
                ('blood', models.CharField(max_length=10)),
                ('plasma', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('hospital', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('date_posted', models.DateField(auto_now=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
