# Generated by Django 3.1.7 on 2021-04-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstore',
            name='area',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
