# Generated by Django 3.1.7 on 2021-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210426_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='plasma',
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
