# Generated by Django 3.1.7 on 2021-05-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210503_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
