# Generated by Django 3.1.7 on 2021-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_posted',
            field=models.CharField(default='2021-05-04', max_length=15),
        ),
    ]
