# Generated by Django 3.1.7 on 2021-05-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210504_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date',
            new_name='date_need',
        ),
    ]
