# Generated by Django 3.1.7 on 2021-05-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210504_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='verified',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_posted',
            field=models.CharField(default='2021-05-21', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
