# Generated by Django 3.1.7 on 2021-05-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210521_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Patient', models.CharField(default='', max_length=100)),
                ('Hospital', models.CharField(default='', max_length=100)),
                ('Messege', models.CharField(default='', max_length=1000)),
                ('date_posted', models.CharField(default='2021-05-25', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_posted',
            field=models.CharField(default='2021-05-25', max_length=15),
        ),
    ]
